Feature/registrar periodo de examen
ritaiglesias-96/gest-edu-front pull request #21
Opened 2024-06-01 21:02 UTC by Adroda

2024-06-02 13:45 UTC, ritaiglesias-96 commented on app/components/List/columnTypes.tsx
>    },
{
    field: 'idAsignatura',
    headerName: '',
    disableColumnMenu: true,
    sortable: false,
    resizable: false,
    cellClassName: 'invisible', // hidden column
    headerClassName: 'invisible', // hidden column
  },
  
  No se si el cambio fue por un save del archivo, pero por las dudas de esa forma queda bien oculta la columna

2024-06-02 13:46 UTC, ritaiglesias-96 requested changes
Pongo esto por las dudas, levantar el proyecto y chequear que ninguna funcionalidad propia o ajena queda afectada. Una vez hecho, lo apruebo

2024-06-02 18:50 UTC, Adroda commented on app/components/List/columnTypes.tsx
>    },
pa te amo rita

2024-06-04 22:15 UTC, ritaiglesias-96 approved these changes

2024-06-04 22:16 UTC, merged