Feature/inscripcion examen fix
ritaiglesias-96/gest-edu-front pull request #22
Opened 2024-06-02 21:22 UTC by mauri1985

![image](https://github.com/ritaiglesias-96/gest-edu-front/assets/30642578/2bf2abbf-19ee-4f9d-83ee-380bc821eae2)

2024-06-04 22:24 UTC, ritaiglesias-96 requested changes

2024-06-04 22:24 UTC, ritaiglesias-96 commented on app/lib/data/coordinador/actions.ts
> -
que pinto?

2024-06-04 22:24 UTC, ritaiglesias-96 commented on app/components/List/list.tsx
Hay que ver aca el temita de las comillas

2024-06-06 22:58 UTC, ritaiglesias-96 requested changes

2024-06-06 22:58 UTC, ritaiglesias-96 commented on app/lib/data/coordinador/actions.ts
> -}
por que se elimina esta funcion?

2024-06-07 01:32 UTC, mauri1985 commented on app/components/List/list.tsx
ya quedo, era un tema de configuracion, me cambio todas las comillas simpler por dobles...

2024-06-07 01:32 UTC, mauri1985 commented on app/lib/data/coordinador/actions.ts
> -}
Vuelvo a agregar, pero no veo donde se usa

2024-06-07 12:13 UTC, ritaiglesias-96 approved these changes

2024-06-07 12:14 UTC, merged