Feature/registrar horario de curso
ritaiglesias-96/gest-edu-front pull request #23
Opened 2024-06-04 03:01 UTC by Adroda

![image](https://github.com/ritaiglesias-96/gest-edu-front/assets/51145626/f786e681-d6b8-4313-b0e7-fc2e6c7e330d)

Siento que el codigo termino medio chancho de todo lo q tuve q probar con varias cosas pero funciona.

Tambien hay un tema de las rutas q estuvimos hablando con diego q hay q ponerse a hablarlo, pero por ahora esta el caso.

2024-06-04 22:24 UTC, ritaiglesias-96 requested changes

2024-06-04 22:24 UTC, ritaiglesias-96 commented on app/lib/data/funcionario/actions.ts
> +};
Algo que hablaba ayer con Diego, veamos de que los Fetch que son comunes a mas de un perfil ponerlos en el actions que esta afuera de las carpetas, esta a la altura de definitions. Asi no repetimos lineas y lineas de codigo.

2024-06-04 22:24 UTC, ritaiglesias-96 commented on app/funcionario/horarios/[id]/[asignaturaId]/page.tsx
> +  }
Sirve hacerlo en utils?

2024-06-04 22:24 UTC, ritaiglesias-96 commented on app/funcionario/horarios/[id]/[asignaturaId]/page.tsx
> +    return `${formattedDay}/${formattedMonth}/${year}`;
Creo que esta funcion la agrego mauri en utils, todo lo que sea funcion de formateo que podamos necesitar en otros componentes por favor mover para ahi

2024-06-04 22:24 UTC, ritaiglesias-96 commented on app/funcionario/horarios/[id]/[asignaturaId]/[cursoId]/horarios.ts
> +];
Lo usas como tipo? podes hacer uno en definitions

2024-06-04 22:30 UTC, Adroda commented on app/funcionario/horarios/[id]/[asignaturaId]/page.tsx
> +  }
Lo puse en utils por si a alguien le llega a ser util pero si queres me lo traigo a donde lo uso nomas

2024-06-04 22:31 UTC, Adroda commented on app/funcionario/horarios/[id]/[asignaturaId]/[cursoId]/horarios.ts
> +];
No, es literal la una lista q guardo pero, era tan larga q preferi ponerlo en un archivo separado

2024-06-04 23:21 UTC, Adroda commented on app/funcionario/horarios/[id]/[asignaturaId]/page.tsx
> +    return `${formattedDay}/${formattedMonth}/${year}`;
Listo

2024-06-05 00:34 UTC, ritaiglesias-96 approved these changes

2024-06-05 00:34 UTC, merged