Feature/RegistrarCalificacionCurso
ritaiglesias-96/gest-edu-front pull request #32
Opened 2024-06-06 03:58 UTC by mauri1985

![image](https://github.com/ritaiglesias-96/gest-edu-front/assets/30642578/3a69b6a4-2c04-4e2c-86b0-83b040189759)

2024-06-06 23:35 UTC, ritaiglesias-96 requested changes

2024-06-06 23:35 UTC, ritaiglesias-96 commented on app/funcionario/calificaciones/[id]/cursos/[cursoId]/page.tsx
> +
Se puede disminuir la cantidad de useEffect?

2024-06-06 23:35 UTC, ritaiglesias-96 commented on app/lib/data/funcionario/actions.ts
> -
Por que se estan eliminando todas estas funciones?

2024-06-06 23:35 UTC, ritaiglesias-96 commented on app/lib/definitions.ts
> -}
OJO con lo que se elimina por favor

2024-06-07 03:29 UTC, mauri1985 commented on app/funcionario/calificaciones/[id]/cursos/[cursoId]/page.tsx
> +
Si, se quitaron tres useEffect

2024-06-07 03:37 UTC, mauri1985 commented on app/lib/data/funcionario/actions.ts
> -
Se volvieron a agregar

2024-06-07 03:38 UTC, mauri1985 commented on app/lib/definitions.ts
> -}
Tambien se volvieron a agregar

2024-06-07 12:12 UTC, ritaiglesias-96 approved these changes

2024-06-07 12:13 UTC, merged